### ISSUE TITLE
web server预览功能

### ISSUE THREAD

**Issue by xuexb** [alafe/wise-sliding#1]
感觉只是本地测试不太帅，要不要搞个web server功能，在外网都能访问到，这样随时都可以快速的看效果～

我想到2种方法：

1. 使用`github pages`功能搭建，不过那样就得往`gh-pages`这个分支推送
1. 使用我的二级域名，如：`ala.xuexb.com`，然后我在我`vpn`上搭建个`server`，并添加推送`hook`

**Comment by xuexb** [comment]
@schoeu 啦啦啦

**Comment by schoeu** [comment]
恩，可以搞个

**Comment by xuexb** [comment]
@schoeu 使用`#1`吧，应该需要有这些注意：

* 域名是：`alafe.github.io/wise-sliding/`
* 注意使用相对路径了
* 使用`ph-pages`分支开发 ps:咱只是写些demo没必要搞多分支开发

容我先创建个试试～
